---
- name: Test the SRC molecule configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create test file
      copy:
        dest: "{{ item['file_name'] }}"
        content: "{{ item['content'] }}"
      with_items: "{{ test_param }}"

    # To test the community.dns collection
    - name: Look up A (IPv4) records for example.org
      ansible.builtin.debug:
        msg: "{{ query('community.dns.lookup', 'example.org.') }}"
