---
- name: Test the SRC molecule configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create test file
      copy:
        dest: "{{ item['file_name'] }}"
        content: "{{ item['content'] }}"
      with_items: "{{ test_param }}"

    # To test the community.general collection
    - name: Convert a duration into weeks
      ansible.builtin.debug:
        msg: "{{ '1y 7m 5d 30h' | community.general.to_weeks }}"
  
